Fix --prefix configuration
git-svn-id: http://root.cern.ch/svn/root/trunk@30011 27541ba8-7e3a-0410-8455-c3a389f83636

diff --git a/cint/configure b/cint/configure
--- a/cint/configure
+++ b/cint/configure
@@ -698,13 +698,15 @@ EXPORTS=(${EXPORTS[*]} HAVE_CONFIG)
 if [ "x$WITHPREFIX" = "x1" ]; then
   # prefix based build
     [ "$PREFIX" = "" ] && PREFIX=/usr/local
-    if [ -d "$PREFIX" -a "`cd \"$PREFIX\"; pwd`" = "`cd \"$PWD\"; pwd`" ]; then
-        echo ' '
-        echo ' '
-        echo 'ERROR: Cannot build within install location!'
-        echo 'Directory '$PREFIX' set as --prefix is the same as the current directory!'
-        echo ' '
-        exit 1
+    if [ -d "$PREFIX" ]; then
+        if [ "`cd \"$PREFIX\"; pwd`" = "`cd \"$PWD\"; pwd`" ]; then
+            echo ' '
+            echo ' '
+            echo 'ERROR: Cannot build within install location!'
+            echo 'Directory '$PREFIX' set as --prefix is the same as the current directory!'
+            echo ' '
+            exit 1
+        fi
     fi
     [ "$EPREFIX" = "" ] && EPREFIX=$PREFIX
     [ "$BINDIR" = "" ]  && BINDIR=$EPREFIX/bin
