re-order Vc tests.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2482,7 +2482,6 @@ llvmdir="/**/"
 if test "x$enable_builtin_llvm" = "x" || \
    test "x$enable_builtin_llvm" = "xno" ; then
     message "Checking for llvm-config for external llvm"
-	
     # allow LLVMDIR instead of --with-llvm-config
     if test "x$llvmconfig" = "x" ; then
         if test ! "x$LLVMDIR" = "x" ; then
@@ -2538,8 +2537,8 @@ if test "x$enable_cocoa" = "xyes"; then
         result "or make sure the desired SDK version is installed"
         exit 1
     else
-	openglincdir=${osxsdk}/System/Library/Frameworks/OpenGL.framework/Headers
-	opengllibdir=${osxsdk}/System/Library/Frameworks/OpenGL.framework/Libraries
+        openglincdir=${osxsdk}/System/Library/Frameworks/OpenGL.framework/Headers
+        opengllibdir=${osxsdk}/System/Library/Frameworks/OpenGL.framework/Libraries
     fi
 fi
 
@@ -2966,8 +2965,8 @@ if test ! "x$enable_opengl" = "xno" && test ! "x$platform" = "xwin32" ; then
     opengllibdir=$found_dir
 
     if test ! "x$macosx105" = "x" && test "x$macosx106" = "x" ; then
-	# Mac OS X 10.5 problem
-	opengllib="-dylib_file /usr/X11R6/lib/libGL.dylib:/usr/X11R6/lib/libGL.dylib -lGL"
+        # Mac OS X 10.5 problem
+        opengllib="-dylib_file /usr/X11R6/lib/libGL.dylib:/usr/X11R6/lib/libGL.dylib -lGL"
     fi
 
     check_library "libGLU libMesaGLU" "$enable_shared" \
@@ -3279,8 +3278,8 @@ if test ! "x$enable_sqlite" = "xno"; then
         /usr/include /usr/local/include \
         /usr/include/sqlite /usr/local/include/sqlite /usr/local/sqlite/include \
         /usr/include/sqlite3 /usr/local/include/sqlite3 /usr/local/sqlite3/include \
-	/usr/sqlite /opt/sqlite /opt/sqlite3/include \
-	/usr/sqlite3 /opt/sqlite3 /opt/sqlite/include
+        /usr/sqlite /opt/sqlite /opt/sqlite3/include \
+        /usr/sqlite3 /opt/sqlite3 /opt/sqlite/include
     sqliteinc=$found_hdr
     sqliteincdir=$found_dir
 
@@ -4861,7 +4860,7 @@ if test "x$enable_xrootd" = "xyes" ; then
          fi
          if test "x$oldver" = "xyes" ; then
             decver=`echo $tmpver | sed 's|[^0-9]||g' | cut -c1-8`
-	 fi
+         fi
       fi
    fi
    # Protect against 3.3.0, first version with 'include/xrootd/private'
@@ -5985,6 +5984,157 @@ result $enable_shadowpw
 check_explicit "$enable_shadowpw" "$enable_shadowpw_explicit" \
      "Explicitly required Shadow passwords dependencies not fulfilled"
 
+##########################################################################
+#
+### echo %%% check for Vc Library compile flags
+#
+avxcxxflag=""
+ssecxxflags=""
+abiversioncxxflag=""
+vcflags=""
+if test "x$enable_vc" = "xyes"; then
+    message "Checking required compiler/assembler workarounds"
+    # with GCC and Open64 check the binutils version. If it's less than 2.18.93 the assembler doesn't know xgetbv
+    case $arch in
+        macos*)
+            as_version="1038000"
+            ;;
+        *)
+            as=`${altcxx} -print-prog-name=as`
+            as_version=`${as} --version|head -n1|sed -e 's/^.*)//' -e 's/^.* \([0-9]\+\.[0-9]\+\.[0-9]\+\).*$/\1/'|awk -F. '{print ($1*1000+$2)*1000+$3}'`
+            ;;
+    esac
+    if test $as_version -lt 2018093; then
+        vcflags="$vcflags -DVC_NO_XGETBV"
+    fi
+    invoke_preprocessor <<EOF
+#define _MAKE_VERSION(A, B, C) A##.##B##.##C
+#define MAKE_VERSION(A, B, C) _MAKE_VERSION(A, B, C)
+#ifdef __INTEL_COMPILER
+ICC
+__INTEL_COMPILER_BUILD_DATE
+#elif defined(__OPENCC__)
+Open64
+#elif defined(__clang__)
+clang
+MAKE_VERSION(__clang_major__, __clang_minor__, __clang_patchlevel__)
+#elif defined(__GNUC__)
+GCC
+MAKE_VERSION(__GNUC__, __GNUC_MINOR__, __GNUC_PATCHLEVEL__)
+#elif defined(_MSC_VER)
+MSVC
+_MSC_FULL_VER
+#else
+UNSUPPORTED_COMPILER
+#endif
+EOF
+    compiler=`echo "$preprocessor_output"|sed '1!d'`
+    compiler_version=`echo "$preprocessor_output"|sed '2!d'|awk -F. '{ print ($1*100+$2)*100+$3 }'`
+    avx_broken=false
+    sse_broken=false
+    xop_broken=false
+    fma4_broken=false
+    case $compiler in
+        ICC)
+            vcflags="$vcflags -diag-disable 913"
+            ;;
+        Open64)
+            avx_broken=true
+            ;;
+        clang)
+            if test $compiler_version -lt 30100; then
+                echo
+                echo "Clang before version 3.1 is unable to compile Vc correctly. Please update clang or disable Vc."
+                exit 1
+            fi
+            ;;
+        GCC)
+            vcflags="$vcflags -Wno-unused-function"
+            if test $compiler_version -lt 40500; then
+                vcflags="$vcflags -Wno-parentheses"
+                if test $compiler_version -lt 40406; then
+                    avx_broken=true
+                    if test $compiler_version -lt 40300; then
+                        sse_broken=true
+                        if test $compiler_version -lt 40200; then
+                            vcflags="$vcflags -fno-strict-aliasing"
+                        fi
+                    fi
+                fi
+            elif test $compiler_version -eq 40600; then
+                avx_broken=true
+            elif test $compiler_version -eq 40700; then
+                vcflags="$vcflags -fno-predictive-commoning"
+            fi
+            if test "x$platform" = "xmacosx" ; then
+                avx_broken=true
+                vcflags="$vcflags -DVC_NO_XGETBV"
+            fi
+            ;;
+        MSVC)
+            vcflags="$vcflags -DNOMINMAX"
+            xop_broken=true
+            fma4_broken=true
+            ;;
+        UNSUPPORTED_COMPILER)
+            ;;
+    esac
+
+    test -n "$vcflags" && result "$vcflags" || result ''
+
+    # check for SIMD compiler flags
+    message "Checking SIMD specific compiler flags"
+    $avx_broken || for flag in '-xAVX' '-mavx' '/arch:AVX'; do
+        check_cxxopt $flag
+        if test $cxxopt_result -eq 1; then
+            avxcxxflag=$flag
+            break;
+        fi
+    done
+    $sse_broken || for tuples in '-xSSE4.1;-msse4.1' '-xSSSE3;-mssse3' '-xSSE3;-msse3' '-xSSE2;-msse2;/arch:SSE2'; do
+        save_IFS="$IFS"
+        IFS=';'
+        for flag in $tuples; do
+            IFS="$save_IFS"
+            check_cxxopt $flag
+            if test $cxxopt_result -eq 1; then
+                ssecxxflags="$ssecxxflags $flag"
+                break;
+            fi
+        done
+    done
+    if test -n "$avxcxxflag" && ! $xop_broken && ! $fma4_broken; then
+        for flag in '-mxop -mfma4'; do
+            check_cxxopt $flag
+            if test $cxxopt_result -eq 1; then
+                flag=`echo $flag|tr ' ' '~'`
+                ssecxxflags="$ssecxxflags -DVC_IMPL=SSE+XOP+FMA4~$flag $avxcxxflag~$flag"
+                break;
+            fi
+        done
+    fi
+    ssecxxflags="${ssecxxflags# }"
+    result "$avxcxxflag $ssecxxflags"
+
+    # check for ABI version compiler flags
+    message "Checking ABI version compiler flags"
+    for flag in '-fabi-version=0' '-fabi-version=4'; do
+        check_cxxopt $flag
+        if test $cxxopt_result -eq 1; then
+            abiversioncxxflag="$flag"
+            break;
+        fi
+    done
+    test -n "$abiversioncxxflag" && result "$abiversioncxxflag" || result 'N/A'
+fi
+
+sed -e "s|@avxcxxflag@|$avxcxxflag|"               \
+    -e "s|@ssecxxflags@|$ssecxxflags|"             \
+    -e "s|@abiversioncxxflag@|$abiversioncxxflag|" \
+    -e "s|@vcflags@|$vcflags|"                     \
+    < Makefile.tmp > Makefile.tmpp
+mv Makefile.tmpp Makefile.tmp
+
 ######################################################################
 #
 ### echo %%% MathMore Library - Contributed library
@@ -6277,164 +6427,6 @@ else
     enable_memstat="no"
 fi
 result $enable_memstat
-
-##########################################################################
-if test "$enable_vc" = 'yes'; then
-    ######################################################################
-    #
-    ### echo %%% check for required compiler/assembler workarounds
-    #
-    message "Checking required compiler/assembler workarounds"
-    vcflags=""
-    # with GCC and Open64 check the binutils version. If it's less than 2.18.93 the assembler doesn't know xgetbv
-    case $arch in
-	macos*)
-	    as_version="1038000"
-	    ;;
-	*)
-	    as=`${altcxx} -print-prog-name=as`
-            as_version=`${as} --version|head -n1|sed -e 's/^.*)//' -e 's/^.* \([0-9]\+\.[0-9]\+\.[0-9]\+\).*$/\1/'|awk -F. '{print ($1*1000+$2)*1000+$3}'`
-	    ;;
-    esac
-    if test $as_version -lt 2018093; then
-	vcflags="$vcflags -DVC_NO_XGETBV"
-    fi
-    invoke_preprocessor <<EOF
-#define _MAKE_VERSION(A, B, C) A##.##B##.##C
-#define MAKE_VERSION(A, B, C) _MAKE_VERSION(A, B, C)
-#ifdef __INTEL_COMPILER
-ICC
-__INTEL_COMPILER_BUILD_DATE
-#elif defined(__OPENCC__)
-Open64
-#elif defined(__clang__)
-clang
-MAKE_VERSION(__clang_major__, __clang_minor__, __clang_patchlevel__)
-#elif defined(__GNUC__)
-GCC
-MAKE_VERSION(__GNUC__, __GNUC_MINOR__, __GNUC_PATCHLEVEL__)
-#elif defined(_MSC_VER)
-MSVC
-_MSC_FULL_VER
-#else
-UNSUPPORTED_COMPILER
-#endif
-EOF
-    compiler=`echo "$preprocessor_output"|sed '1!d'`
-    compiler_version=`echo "$preprocessor_output"|sed '2!d'|awk -F. '{ print ($1*100+$2)*100+$3 }'`
-    avx_broken=false
-    sse_broken=false
-    xop_broken=false
-    fma4_broken=false
-    case $compiler in
-        ICC)
-            vcflags="$vcflags -diag-disable 913"
-            ;;
-        Open64)
-            avx_broken=true
-            ;;
-        clang)
-            if test $compiler_version -lt 30100; then
-                echo
-                echo "Clang before version 3.1 is unable to compile Vc correctly. Please update clang or disable Vc."
-                exit 1
-            fi
-            ;;
-        GCC)
-            vcflags="$vcflags -Wno-unused-function"
-            if test $compiler_version -lt 40500; then
-                vcflags="$vcflags -Wno-parentheses"
-                if test $compiler_version -lt 40406; then
-                    avx_broken=true
-                    if test $compiler_version -lt 40300; then
-                        sse_broken=true
-                        if test $compiler_version -lt 40200; then
-                            vcflags="$vcflags -fno-strict-aliasing"
-                        fi
-                    fi
-                fi
-            elif test $compiler_version -eq 40600; then
-                avx_broken=true
-            elif test $compiler_version -eq 40700; then
-                vcflags="$vcflags -fno-predictive-commoning"
-            fi
-            if test "x$platform" = "xmacosx" ; then
-                avx_broken=true
-                vcflags="$vcflags -DVC_NO_XGETBV"
-            fi
-            ;;
-        MSVC)
-            vcflags="$vcflags -DNOMINMAX"
-            xop_broken=true
-            fma4_broken=true
-            ;;
-        UNSUPPORTED_COMPILER)
-            ;;
-    esac
-
-    test -n "$vcflags" && result "$vcflags" || result ''
-
-    ######################################################################
-    #
-    ### echo %%% check for SIMD compiler flags
-    #
-    message "Checking SIMD specific compiler flags"
-    avxcxxflag=""
-    $avx_broken || for flag in '-xAVX' '-mavx' '/arch:AVX'; do
-        check_cxxopt $flag
-        if test $cxxopt_result -eq 1; then
-            avxcxxflag=$flag
-            break;
-        fi
-    done
-    ssecxxflags=""
-    $sse_broken || for tuples in '-xSSE4.1;-msse4.1' '-xSSSE3;-mssse3' '-xSSE3;-msse3' '-xSSE2;-msse2;/arch:SSE2'; do
-        save_IFS="$IFS"
-        IFS=';'
-        for flag in $tuples; do
-            IFS="$save_IFS"
-            check_cxxopt $flag
-            if test $cxxopt_result -eq 1; then
-                ssecxxflags="$ssecxxflags $flag"
-                break;
-            fi
-        done
-    done
-    if test -n "$avxcxxflag" && ! $xop_broken && ! $fma4_broken; then
-        for flag in '-mxop -mfma4'; do
-            check_cxxopt $flag
-            if test $cxxopt_result -eq 1; then
-                flag=`echo $flag|tr ' ' '~'`
-                ssecxxflags="$ssecxxflags -DVC_IMPL=SSE+XOP+FMA4~$flag $avxcxxflag~$flag"
-                break;
-            fi
-        done
-    fi
-    ssecxxflags="${ssecxxflags# }"
-    result "$avxcxxflag $ssecxxflags"
-
-    ######################################################################
-    #
-    ### echo %%% check for ABI version compiler flags
-    #
-    message "Checking ABI version compiler flags"
-    abiversioncxxflag=""
-    for flag in '-fabi-version=0' '-fabi-version=4'; do
-        check_cxxopt $flag
-        if test $cxxopt_result -eq 1; then
-            abiversioncxxflag="$flag"
-            break;
-        fi
-    done
-    test -n "$abiversioncxxflag" && result "$abiversioncxxflag" || result 'N/A'
-
-    sed -e "s|@avxcxxflag@|$avxcxxflag|"               \
-        -e "s|@ssecxxflags@|$ssecxxflags|"             \
-        -e "s|@abiversioncxxflag@|$abiversioncxxflag|" \
-        -e "s|@vcflags@|$vcflags|" \
-        < Makefile.tmp > Makefile.tmpp
-    mv Makefile.tmpp Makefile.tmp
-fi
 
 ######################################################################
 #
