Copy vdt and vc form master in 5.34 branch

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -102,6 +102,8 @@ options="                    \
    enable_table              \
    enable_tmva               \
    enable_unuran             \
+   enable_vc                 \
+   enable_vdt                \
    enable_winrtdebug         \
    enable_x11                \
    enable_xft                \
@@ -161,6 +163,7 @@ enable_soversion=no
 enable_table=no
 enable_thread=yes        # cannot be disabled (not in above options list)
 enable_unuran=no
+enable_vc=no
 enable_winrtdebug=
 enable_builtin_freetype=no
 enable_builtin_ftgl=no
@@ -179,6 +182,8 @@ if test "x$ENABLEALL" = "xyes"; then
     enable_ruby=yes
     enable_table=yes
     enable_unuran=yes
+    enable_vc=yes
+    enable_vdt=yes
 fi
 
 # Remove old log file
@@ -228,6 +233,7 @@ MINUIT2          \
 TABLE            \
 XMLDIR           \
 ROOTDICTTYPE     \
+VC               \
 DAVIX            \
 "
 configenvvars=
@@ -1632,6 +1638,7 @@ enable/disable options, prefix with either --enable- or --disable-
   ssl                SSL encryption support, requires openssl
   table              Build libTable contrib library
   tmva               Build TMVA multi variate analysis library
+  vc                 Vc adds a few new types for portable and intuitive SIMD programming
   unuran             UNURAN - package for generating non-uniform random numbers
   winrtdebug         Link against the Windows debug runtime library
   x11                X11 support
@@ -5987,6 +5994,161 @@ result $enable_shadowpw
 check_explicit "$enable_shadowpw" "$enable_shadowpw_explicit" \
      "Explicitly required Shadow passwords dependencies not fulfilled"
 
+##########################################################################
+#
+### echo %%% check for Vc Library compile flags
+#
+avxcxxflag=""
+ssecxxflags=""
+abiversioncxxflag=""
+vcflags=""
+if test "x$enable_vc" = "xyes"; then
+    message "Checking required compiler/assembler workarounds"
+    # with GCC and Open64 check the binutils version. If it's less than 2.18.93 the assembler doesn't know xgetbv
+    case $arch in
+	macos*)
+	    ;;
+	*)
+	    as=`${altcxx} -print-prog-name=as`
+            as_version=`${as} --version|head -n1|sed -e 's/^.*)//' -e 's/^.* \([0-9]\+\.[0-9]\+\.[0-9]\+\).*$/\1/'|awk -F. '{print ($1*1000+$2)*1000+$3}'`
+	    if test $as_version -lt 2018093; then
+		vcflags="$vcflags -DVC_NO_XGETBV"
+	    fi
+	    ;;
+    esac
+    invoke_preprocessor <<EOF
+#define _MAKE_VERSION(A, B, C) A##.##B##.##C
+#define MAKE_VERSION(A, B, C) _MAKE_VERSION(A, B, C)
+#ifdef __INTEL_COMPILER
+ICC
+__INTEL_COMPILER_BUILD_DATE
+#elif defined(__OPENCC__)
+Open64
+#elif defined(__clang__)
+clang
+MAKE_VERSION(__clang_major__, __clang_minor__, __clang_patchlevel__)
+#elif defined(__GNUC__)
+GCC
+MAKE_VERSION(__GNUC__, __GNUC_MINOR__, __GNUC_PATCHLEVEL__)
+#elif defined(_MSC_VER)
+MSVC
+_MSC_FULL_VER
+#else
+UNSUPPORTED_COMPILER
+#endif
+EOF
+    compiler=`echo "$preprocessor_output"|sed '1!d'`
+    compiler_version=`echo "$preprocessor_output"|sed '2!d'|awk -F. '{ print ($1*100+$2)*100+$3 }'`
+    avx_broken=false
+    sse_broken=false
+    xop_broken=false
+    fma4_broken=false
+    case $compiler in
+        ICC)
+            vcflags="$vcflags -diag-disable 913"
+            ;;
+        Open64)
+            avx_broken=true
+            ;;
+        clang)
+            if test $compiler_version -lt 30100; then
+                echo
+                echo "Clang before version 3.1 is unable to compile Vc correctly. Please update clang or disable Vc."
+                exit 1
+            fi
+            ;;
+        GCC)
+            vcflags="$vcflags -Wno-unused-function"
+            if test $compiler_version -lt 40500; then
+                vcflags="$vcflags -Wno-parentheses  -Wno-strict-aliasing -Wno-uninitialized"
+                if test $compiler_version -lt 40406; then
+                    avx_broken=true
+                    if test $compiler_version -lt 40300; then
+                        sse_broken=true
+                        if test $compiler_version -lt 40200; then
+                            vcflags="$vcflags -fno-strict-aliasing"
+                        fi
+                    fi
+                fi
+            elif test $compiler_version -eq 40600; then
+                avx_broken=true
+            elif test $compiler_version -eq 40700; then
+                vcflags="$vcflags -fno-predictive-commoning"
+            fi
+            if test "x$platform" = "xmacosx" ; then
+                avx_broken=true
+                vcflags="$vcflags -DVC_NO_XGETBV"
+            fi
+            ;;
+        MSVC)
+            vcflags="$vcflags -DNOMINMAX"
+            xop_broken=true
+            fma4_broken=true
+            ;;
+        UNSUPPORTED_COMPILER)
+            ;;
+    esac
+
+    test -n "$vcflags" && result "$vcflags" || result ''
+
+    # check for SIMD compiler flags
+    message "Checking SIMD specific compiler flags"
+    $avx_broken || for flag in '-xAVX' '-mavx' '/arch:AVX'; do
+        check_cxxopt $flag
+        if test $cxxopt_result -eq 1; then
+            avxcxxflag=$flag
+            break;
+        fi
+    done
+    $sse_broken || for tuples in '-xSSE4.1;-msse4.1' '-xSSSE3;-mssse3' '-xSSE3;-msse3' '-xSSE2;-msse2;/arch:SSE2'; do
+        save_IFS="$IFS"
+        IFS=';'
+        for flag in $tuples; do
+            IFS="$save_IFS"
+            check_cxxopt $flag
+            if test $cxxopt_result -eq 1; then
+                ssecxxflags="$ssecxxflags $flag"
+                break;
+            fi
+        done
+    done
+    if test -n "$avxcxxflag" && ! $xop_broken && ! $fma4_broken; then
+        for flag in '-mxop -mfma4'; do
+            check_cxxopt $flag
+            if test $cxxopt_result -eq 1; then
+                flag=`echo $flag|tr ' ' '~'`
+                ssecxxflags="$ssecxxflags -DVC_IMPL=SSE+XOP+FMA4~$flag $avxcxxflag~$flag"
+                break;
+            fi
+        done
+    fi
+    ssecxxflags="${ssecxxflags# }"
+    result "$avxcxxflag $ssecxxflags"
+
+    # check for ABI version compiler flags
+    case $compiler in
+	GCC)
+	    message "Checking ABI version compiler flags"
+	    abiversioncxxflag=""
+	    for flag in '-fabi-version=0' '-fabi-version=4'; do
+		check_cxxopt $flag
+		if test $cxxopt_result -eq 1; then
+		    abiversioncxxflag="$flag"
+		    break;
+		fi
+	    done
+	    test -n "$abiversioncxxflag" && result "$abiversioncxxflag" || result 'N/A'
+    esac
+fi
+
+sed -e "s|@avxcxxflag@|$avxcxxflag|"               \
+    -e "s|@ssecxxflags@|$ssecxxflags|"             \
+    -e "s|@abiversioncxxflag@|$abiversioncxxflag|" \
+    -e "s|@vcflags@|$vcflags|"                     \
+    < Makefile.tmp > Makefile.tmpp
+mv Makefile.tmpp Makefile.tmp
+
+
 ######################################################################
 #
 ### echo %%% MathMore Library - Contributed library
@@ -6256,6 +6418,37 @@ fi
 
 ######################################################################
 #
+### echo %%% Vc Library - Contributed library
+#
+message "Checking whether to build libVc"
+if test "x$enable_vc" = "xyes" || test ! "x$VC" = "x"; then
+    enable_vc="yes"
+    result "yes"
+    hasvc="define"
+else
+    enable_vc=""
+    result "no"
+    hasvc="undef"
+fi
+
+######################################################################
+#
+### echo %%% VDT Library - Contributed library
+#
+message "Checking whether to install VDT"
+if test "x$enable_vdt" = "xyes" || test ! "x$VC" = "x"; then
+    enable_vdt="yes"
+    result "yes"
+    hasvdt="define"
+else
+    enable_vdt=""
+    result "no"
+    hasvdt="undef"
+fi
+
+
+######################################################################
+#
 ### echo %%% GDML Library - Contributed library
 #
 message "Checking whether to build libGdml"
@@ -6437,6 +6630,8 @@ if test "x$show_pkglist" = "xyes" ; then
     test "x$enable_xml"      = "xyes" && pl="$pl libroot-io-xmlparser"
     test "x$enable_mathmore" = "xyes" && pl="$pl libroot-math-mathmore"
     test "x$enable_unuran"   = "xyes" && pl="$pl libroot-math-unuran"
+    test "x$enable_vc"       = "xyes" && pl="$pl libroot-math-vc"
+    test "x$enable_vdt"      = "xyes" && pl="$pl libroot-math-vdt"
     test "x$enable_table"    = "xyes" && pl="$pl libroot-misc-table"
     test "x$enable_ldap"     = "xyes" && pl="$pl libroot-net-ldap"
     test "x$enable_roofit"   = "xyes" && pl="$pl libroot-roofit"
@@ -6900,6 +7095,8 @@ sed -e "s|@aclocaldir@|$aclocaldir|"            \
     -e "s|@buildroofit@|$enable_roofit|"        \
     -e "s|@buildminuit2@|$enable_minuit2|"      \
     -e "s|@buildunuran@|$enable_unuran|"        \
+    -e "s|@buildvc@|$enable_vc|"                \
+    -e "s|@buildvdt@|$enable_vdt|"              \
     -e "s|@buildgdml@|$enable_gdml|"            \
     -e "s|@buildmonalisa@|$enable_monalisa|"    \
     -e "s|@buildtable@|$enable_table|"          \
@@ -7145,6 +7342,7 @@ sed \
     -e "s|@hasxft@|$hasxft|"               \
     -e "s|@hascling@|$hascling|"           \
     -e "s|@hascocoa@|$hascocoa|"           \
+    -e "s|@hasvc@|$hasvc|"                 \
     -e "s|@usec++11@|$usecxx11|"           \
     -e "s|@uselibc++@|$uselibcxx|"         \
     < RConfigure.tmp > RConfigure-out.tmp
