From Antonio Salvucci: updates to the Debian packaging infrastructure.
git-svn-id: http://root.cern.ch/svn/root/trunk@38489 27541ba8-7e3a-0410-8455-c3a389f83636

diff --git a/build/package/debian/root-system-rootd.prerm b/build/package/debian/root-system-rootd.prerm
--- a/build/package/debian/root-system-rootd.prerm
+++ b/build/package/debian/root-system-rootd.prerm
@@ -3,6 +3,7 @@
 #
 # see: dh_installdeb(1)
 
+# Do not set - If we cannot remove the rootd user, it is OK
 set -e
 
 case "$1" in
@@ -10,6 +11,26 @@ case "$1" in
 	if grep ^rootd /etc/inetd.conf > /dev/null 2>&1 ; then
 	  update-inetd --remove rootd
 	fi
+	# Remove the rootd user and group 
+	# Taken from mysql-server package and modified for ROOT 
+        # rm -rf /var/spool/rootd
+	if getent passwd rootd > /dev/null; then 
+	    deluser --remove-home rootd
+	    reason=$?
+            if [ $reason -ne 0 ] ; then 
+	        # Could not remove user. Ignore. 
+		echo "Couldn't remove user rootd, check it. Reason"
+		case $reason in 
+		    1)  echo "can't update password file"     ;;
+		    2)  echo "bad command syntax"             ;;
+		    6)  echo "specified user doesn't exist"   ;;
+		    8)  echo "user currently logged in"       ;;
+		    10) echo "can't update group file"        ;; 
+		    12) echo "can't remove home directory"    ;;
+		    *)  echo "Unrecognized exit code $reason" ;;
+		esac
+	    fi
+	fi	
 	;;
     upgrade|deconfigure)
 	# Nothing to be done here 
@@ -21,6 +42,9 @@ case "$1" in
         exit 0
     ;;
 esac
+
+# Now we set fail-on-sub-error so that the debhelper stuff is done correctly. 
+# set -e 
 
 # dh_installdeb will replace this with shell code automatically
 # generated by other debhelper scripts.
diff --git a/build/package/debian/ttf-root-installer.postinst.in b/build/package/debian/ttf-root-installer.postinst.in
--- a/build/package/debian/ttf-root-installer.postinst.in
+++ b/build/package/debian/ttf-root-installer.postinst.in
@@ -36,16 +36,23 @@ case "$1" in
 		| grep -v "symbol.ttf" > /var/cache/ttf-root-installer
 	    tar -xzf $archive 
 	    mkdir -p @prefix@/share/root/fonts/
-	    for i in ttf/fonts/*.ttf ; do 
+	    cd ttf/fonts/
+	    for i in *.ttf ; do 
 		case $i in 
 		    *symbol.ttf) ;; # ignore this one 
 		    *)
-			cp -a $i @prefix@/share/root/fonts/
+			if grep $i /var/lib/ttf-root-installer/sha256sums | sha256sum -c ; then 
+			    cp -a $i @prefix@/share/root/fonts/
+			else 
+			    echo "Checksum mismatch for $i, aborting"
+			    exit 1
+			fi
 			;;
 		esac
 	    done
-	    cp ttf/fonts/LICENSE \
+	    cp LICENSE \
 		@prefix@/share/doc/ttf-root-installer/LICENSE.fonts
+	    cd ../../
 	    rm -rf ttf
 	    
 	    if test "x$SAVEDIR" != "x" ; then 
