From Christian Holm: I've made a patch for some updates to the packaging stuff in ROOT.
The most important change is, that in Debian and Redhat packages
`libroot', I install the libraries in `/usr/lib/root/<version>' (where
version is something like 5.03), and I put symbolic links to the ROOT
libraries in `/usr/lib/root'

        /usr/lib/root/libTreePlayer.so.5.03 -> /usr/lib/root/5.03/libTreePlayer.so.5.03
        /usr/lib/root/libTreePlayer.so -> /usr/lib/root/5.03/libTreePlayer.so.5.03

And in `/etc/root/system.rootrc' we get

	Unix.Root.*.DynamicPath: .:/usr/lib/root/5.03

This allows users to only install `libroot' and not be forced to install
`libroot-dev' for the dynamic loading of ROOT plugins to work.

It also means, that users can more easily upgrade ROOT.  That is,
suppose you have `libroot' version 4.04.03 installed, and you have some
application that depends on that, say `mn-fit'.  Now, you want to
upgrade to the next production version, say 5.03.01, but `mn-fit' hasn't
been recompiled against the new ROOT libraries.   As the libraries in
`libroot' are all versioned (end in `.so.<version>'), the two version of
`libroot' can easily co-exist.  However, the libraries should load the
correct libraries for the particular version, which is ensured by the
line in `/etc/root/system.rootrc'.  The name of the package `libroot' is
changed to `libroot<major>' where <major> is the major version number of
ROOT (e.g., `5').

For the packages, root-rootd, and root-proofd, I removed the (X)Inetd
stuff, so that these services should be started by SYSV Init scripts
instead.

Also, I updated the `README/INSTALL' file to address some recent
complaints about the RPM building.  I also added section numbers and a
Table of Contents.

In `configure', I added the directory `/usr/include/postgresql/8.0' to
the search path for `lib-pq.h', as that's where the headers are put now
a days on Debian `sid'.

In `xrootd/Module.mk', I took out the `xrdpwdgsi' executable from the
`ALLEXECS' variable, as it doesn't seem to be build.

I added the man page `xrdpwdadmin.1'.


git-svn-id: http://root.cern.ch/svn/root/trunk@12478 27541ba8-7e3a-0410-8455-c3a389f83636

diff --git a/build/package/debian/root-proofd.init.in b/build/package/debian/root-proofd.init.in
--- a/build/package/debian/root-proofd.init.in
+++ b/build/package/debian/root-proofd.init.in
@@ -53,17 +53,23 @@ case `echo $ENABLE_PROOFD | tr '[:upper:]' '[:lower:]'` in
     *) exit 0;;
 esac
 
-set -e
-
 startit ()
 {
     start-stop-daemon --make-pidfile --start --quiet --pidfile \
 	/var/run/$NAME.pid --exec $DAEMON -- $DAEMON_OPTS $PROOF_DIR
+    if test $? -ne 0 ; then 
+	echo "Failed" 
+	exit 1
+    fi
 }
 stopit ()
 {
     start-stop-daemon --stop --quiet --pidfile /var/run/$NAME.pid \
 	--exec $DAEMON $REDIR
+    if test $? -ne 0 ; then 
+	echo "Failed" 
+	exit 1
+    fi
 }
 
 case "$1" in
diff --git a/build/package/debian/root-rootd.init.in b/build/package/debian/root-rootd.init.in
--- a/build/package/debian/root-rootd.init.in
+++ b/build/package/debian/root-rootd.init.in
@@ -1,4 +1,4 @@
-#! /bin/sh
+#! /bin/bash
 #
 # skeleton	Written by Miquel van Smoorenburg <miquels@cistron.nl>.
 #		Modified for Debian 
@@ -22,10 +22,10 @@ fi
 if test ! "x$ROOTD_USER" = "x" ; then 
     USER=$ROOTD_USER
 fi
-if test "x$ROOTD_PORT" = "x" ; then 
+if test ! "x$ROOTD_PORT" = "x" ; then 
     DAEMON_OPTS="-p $ROOTD_PORT"
 fi
-if test "x$SSH_PORT" = "x" ; then 
+if test ! "x$SSH_PORT" = "x" ; then 
     DAEMON_OPTS="-s $SSH_PORT"
 fi
 
@@ -64,14 +64,17 @@ case `echo $ENABLE_ROOTD | tr '[:upper:]' '[:lower:]'` in
     *) exit 0;;
 esac
 
-set -e
-
 	
 startit() 
 {
     o=`start-stop-daemon --chuid $USER --start --quiet --pidfile \
 	/var/run/$NAME.pid --exec $DAEMON -- $DAEMON_OPTS`
+    if test $? -ne 0 ; then 
+	echo "Failed: $o" 
+	exit 1
+    fi
     eval $o
+    echo " (pid: $ROOTD_PID) "
     echo $ROOTD_PID > /var/run/$NAME.pid
 }
 
@@ -79,6 +82,10 @@ stopit()
 {
     start-stop-daemon --user $USER --stop --quiet --pidfile \
 	/var/run/$NAME.pid --exec $DAEMON
+    if test $? -ne 0 ; then 
+	echo "Failed: $o" 
+	exit 1
+    fi
     rm -f /var/run/$NAME.pid
 }
 
diff --git a/build/package/debian/root-xrootd.init.in b/build/package/debian/root-xrootd.init.in
--- a/build/package/debian/root-xrootd.init.in
+++ b/build/package/debian/root-xrootd.init.in
@@ -60,7 +60,7 @@ fi
 if test "x$XROOTD_USER" = "xroot" ; then 
     :
 elif test "x$XROOTD_USER" != "x" ; then 
-    USER=XROOTD_USER
+    USER=$XROOTD_USER
 fi
 
 case $enable_rootd:$enable_olbd in 
@@ -69,30 +69,45 @@ case $enable_rootd:$enable_olbd in
     *) exit 0;;
 esac
 
-set -e
 
 startitx ()
 {
     start-stop-daemon --make-pidfile --chuid $USER --start --quiet \
 	--pidfile /var/run/$XNAME.pid --exec $XDAEMON \
 	--background -- $XDAEMON_OPTS
+    if test $? -ne 0 ; then 
+	echo "Failed" 
+	exit 1
+    fi
 }
 startito ()
 {
     start-stop-daemon --make-pidfile --chuid $USER --start --quiet \
 	--pidfile /var/run/$XNAME.pid --exec $ODAEMON \
 	---background - $ODAEMON_OPTS
+    if test $? -ne 0 ; then 
+	echo "Failed" 
+	exit 1
+    fi
 }
 
 stopitx() 
 {
     start-stop-daemon --user $USER --stop --quiet --pidfile \
 	/var/run/$XNAME.pid --exec $XDAEMON 
+    if test $? -ne 0 ; then 
+	echo "Failed" 
+	exit 1
+    fi
 }
 stopito()
 {
     start-stop-daemon --user $USER --stop --quiet --pidfile \
 	/var/run/$ONAME.pid --exec $ODAEMON 
+    if test $? -ne 0 ; then 
+	echo "Failed" 
+	exit 1
+    fi
 }
 case "$1" in
   start)
