This commit was manufactured by cvs2svn to create tag 'v2-26-00'.
git-svn-id: http://root.cern.ch/svn/root/tags/v2-26-00@3885 27541ba8-7e3a-0410-8455-c3a389f83636

diff --git a/config/root-config.in b/config/root-config.in
--- a/config/root-config.in
+++ b/config/root-config.in
@@ -1,27 +1,28 @@
 #!/bin/sh
-# -*- sh-indentation: 3 -*-
+
 # This script returns the machine dependent compile options needed
 # to compile and link applications using the ROOT libraries.
 #
 # Author: Fons Rademakers, 06/06/99
 
 arch=@architecture@
-libdir=@libdir@
-incdir=@incdir@
-if test "$arch" = "win32gdk"; then
-   arch="win32"
-fi
-if test "$arch" = "win32"; then
-   incdir=`cygpath -u $incdir`
-   libdir=`cygpath -u $libdir`
-fi
 
 ### ROOT libraries ###
 
-newlib="-lNew"
-rootlibs="-lCore -lCint -lHist -lGraf -lGraf3d -lGpad -lTree -lRint \
-          -lPostscript -lMatrix -lPhysics"
-rootglibs="-lGui"
+if [ "$arch" = "win32" ]; then
+   newlib="%prefix%/libNew.lib"
+   rootlibs="%prefix%/libCore.lib %prefix%/libCint.lib %prefix%/libHist.lib \
+             %prefix%/libGraf.lib %prefix%/libGraf3d.lib %prefix%/libGpad.lib \
+             %prefix%/libTree.lib %prefix%/libRint.lib \
+             %prefix%/libPostscript.lib %prefix%/libMatrix.lib \
+             %prefix%/libPhysics.lib"
+   rootglibs="%prefix%/libGui.lib"
+else
+   newlib="-lNew"
+   rootlibs="-lCore -lCint -lHist -lGraf -lGraf3d -lGpad -lTree -lRint \
+             -lPostscript -lMatrix -lPhysics"
+   rootglibs="-lGui"
+fi
 
 ### machine dependent settings ###
 
@@ -32,9 +33,9 @@ hpux)
    auxlibs="-lm -ldld"
    auxglibs=${auxlibs}
    ;;
-hpuxacc | hpuxia64acc)
+hpuxacc)
    # HP-UX 10.x with aCC
-   auxcflags="-DR__ACC"
+   auxcflags="+W823"
    auxlibs="-lm -ldld"
    auxglibs=${auxlibs}
    ;;
@@ -44,13 +45,7 @@ hpuxegcs)
    auxlibs="-lm -ldld"
    auxglibs=${auxlibs}
    ;;
-hurddeb)
-   # Debian GNU/Hurd
-   auxcflags=
-   auxlibs="-lnsl -lm -ldl -rdynamic"
-   auxglibs=${auxlibs}
-   ;;
-aix | aix5)
+aix)
    # IBM AIX
    auxcflags="-qnoro -qnoroconst -qmaxmem=-1"
    auxlibs=
@@ -82,8 +77,8 @@ solarisgcc)
    ;;
 solarisCC5)
    # Solaris CC 5.0
-   auxcflags=
-   auxlibs="-lm -ldl -lnsl -lsocket"
+   auxcflags="-D__SunOS_5_6 -library=iostream,no%Cstd"
+   auxlibs="-library=iostream,no%Cstd -lm -ldl -lnsl -lsocket"
    auxglibs=${auxlibs}
    ;;
 solariskcc)
@@ -100,7 +95,7 @@ solarisx86)
    ;;
 sgicc)
    # SGI
-   auxcflags="-LANG:std"
+   auxcflags=
    auxlibs="-lm -ldl"
    auxglibs=${auxlibs}
    ;;
@@ -153,19 +148,19 @@ alphacxx)
    auxlibs="-lm"
    auxglibs=${auxlibs}
    ;;
-linuxrh42 | linuxrh51)
+linux|linuxrh42)
    # Linux with gcc 2.7.2.x
    auxcflags=
    auxlibs="-lg++ -lm -ldl -rdynamic"
    auxglibs=${auxlibs}
    ;;
-linux)
-   # Linux with egcs, gcc 2.9x, gcc 3.x
+linuxegcs)
+   # Linux with egcs
    auxcflags="-D_REENTRANT"
    auxlibs="-lm -ldl -lpthread -rdynamic"
    auxglibs=${auxlibs}
    ;;
-linuxdeb | linuxsuse6)
+linuxdeb|linuxsuse6)
    # Linux with egcs on Debian and SuSE
    auxcflags=
    auxlibs="-lm -ldl -rdynamic"
@@ -183,12 +178,6 @@ linuxkcc)
    auxlibs="-lm -ldl -rdynamic"
    auxglibs=${auxlibs}
    ;;
-linuxicc)
-   # Linux with the Intel icc compiler
-   auxcflags=
-   auxlibs="-lm -ldl"
-   auxglibs=${auxlibs}
-   ;;
 linuxppcegcs)
    # Linux/ppc with gcc/glibc
    auxcflags="-fsigned-char -I/usr/X11/include"
@@ -196,32 +185,14 @@ linuxppcegcs)
    auxglibs=${auxlibs}
    ;;
 linuxia64gcc)
-   # Itanium Linux with gcc 2.x/3.x
+   # Itanium Linux with gcc 2.9x
    auxcflags=
    auxlibs="-lm -ldl -rdynamic"
-   auxglibs=${auxlibs}
-   ;;
-linuxia64sgi)
-   # Itanium Linux with SGI compiler
-   auxcflags=
-   auxlibs="-lm -ldl"
-   auxglibs=${auxlibs}
-   ;;
-linuxia64ecc)
-   # Itanium Linux with Intel ecc compiler
-   auxcflags=
-   auxlibs="-lm -ldl"
    auxglibs=${auxlibs}
    ;;
 linuxalphaegcs)
    # Alpha Linux with egcs
    auxcflags=
-   auxlibs="-lm -ldl -rdynamic"
-   auxglibs=${auxlibs}
-   ;;
-linuxarm)
-   # ARM Linux with egcs
-   auxcflags="-fsigned-char"
    auxlibs="-lm -ldl -rdynamic"
    auxglibs=${auxlibs}
    ;;
@@ -241,12 +212,6 @@ freebsd4)
    # FreeBSD with glibc
    auxcflags=
    auxlibs="-lm -lstdc++"
-   auxglibs=${auxlibs}
-   ;;
-macosx)
-   # MacOS X with cc (GNU cc v2.95.2.)
-   auxcflags=
-   auxlibs="-lm -ldl"
    auxglibs=${auxlibs}
    ;;
 hiux)
@@ -272,228 +237,109 @@ esac
 
 
 prefix=@prefix@
-if test "$arch" = "win32"; then
+if [ "$arch" = "win32" ]; then
    prefix=`cygpath -u ${prefix}`
 fi
 exec_prefix=${prefix}
 exec_prefix_set=no
-new_set=no
-libsout=no
-cflags=""
-noauxlibs=no
-noauxcflags=no
-noldflags=no
+nonew_set=no
 
 usage="\
-Usage: root-config [--prefix[=DIR]] [--exec-prefix[=DIR]] [--version] [--cflags] [--new] [--nonew] [--libs] [--glibs] [--libdir] [--incdir] [--noauxcflags] [--noauxlibs] [--noldflags] [--help]"
+Usage: root-config [--prefix[=DIR]] [--exec-prefix[=DIR]] [--version] [--nonew] [--libs] [--glibs] [--cflags]"
 
 if test $# -eq 0; then
-   echo "${usage}" 1>&2
-   exit 1
+      echo "${usage}" 1>&2
+      exit 1
 fi
-
-out=""
 
 while test $# -gt 0; do
   case "$1" in
   -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
-  *)    optarg= ;;
+  *) optarg= ;;
   esac
 
   case $1 in
     --prefix=*)
-      ### Set the prefix
-      if test "$arch" = "win32"; then
+      if [ "$arch" = "win32" ]; then
          optarg=`cygpath -u $optarg`
       fi
       prefix=$optarg
-      incdir=${prefix}/include
-      libdir=${prefix}/lib
-      ### We need to expand the path to backslash seperated path
-      if test "$arch" = "win32"; then
-         incdir=`cygpath -u $incdir`
-         libdir=`cygpath -u $libdir`
-      fi
       if test $exec_prefix_set = no ; then
-         exec_prefix=$optarg
+        exec_prefix=$optarg
       fi
       ;;
     --prefix)
-      ### Output the prefix
-      out="$out $prefix"
+      echo $prefix
       ;;
     --exec-prefix=*)
-      ### Set the exec-prefix
-      if test "$arch" = "win32"; then
+      if [ "$arch" = "win32" ]; then
          optarg=`cygpath -u $optarg`
       fi
       exec_prefix=$optarg
       exec_prefix_set=yes
-      libdir=${exec_prefix}/lib
-      ### We need to expand the path to backslash seperated path
-      if test "$arch" = "win32"; then
-         libdir=`cygpath -u $libdir`
-      fi
       ;;
     --exec-prefix)
-      ### Output the exec-prefix
-      out="$out $prefix"
+      echo $exec_prefix
       ;;
     --nonew)
-      ### Don't use the libNew library
-      new_set="no"
-      ;;
-    --new)
-      ### Use the libNew library
-      new_set="yes"
-      ;;
-    --noauxlibs)
-      noauxlibs="yes"
-      ;;
-    --noauxcflags)
-      noauxcflags="yes"
-      ;;
-    --noldflags)
-      noldflags="yes"
+      nonew_set=yes
       ;;
     --version)
-      ### Output the version number.  If RVersion.h can not be found, give up.
-      if test -r ${incdir}/RVersion.h; then
-         out="$out `sed -n 's,.*ROOT_RELEASE *\"\(.*\)\".*,\1,p' < ${incdir}/RVersion.h`"
+      if test -r ${prefix}/include/RVersion.h ; then
+         echo `cat ${prefix}/include/RVersion.h | sed -e "s/.*ROOT_RELEASE //" \
+               -e "s/.*#.*$//" -e "s/.*\*.*$//" -e "s/\"//g" -e "/^$/d"`
       else
-         echo "cannot read ${incdir}/RVersion.h"
-         exit 1
+         echo "cannot read ${prefix}/include/RVersion.h"
       fi
       ;;
     --cflags)
-      ### Output the compiler flags
-      if test ${incdir} != /usr/include; then
-         ### In case we're on a Win32 system, we need to expand the
-         ### path to a backslash seperated path
-         if test "$arch" = "win32"; then
-            includes=-I\'`cygpath -w ${incdir}`\'
+      if test ${prefix}/include != /usr/include ; then
+         if [ "$arch" = "win32" ]; then
+            includes=-I\'`cygpath -w ${prefix}/include`\'
          else
-            includes=-I${incdir}
+            includes=-I${prefix}/include
          fi
       fi
-      if test "x$noauxcflags" = "xyes" ; then
-         out="$out $includes"
-      else
-         out="$out ${auxcflags} $includes"
-      fi
-      ;;
-   --auxcflags)
-      ### output auxiliary compiler flags
-      out="$out $auxcflags"
+      echo ${auxcflags} $includes
       ;;
     --libs)
-      ### Output regular ROOT libraries.  If the user said --glibs --libs,
-      ### We've already output the libraries, so we skip this section
-      if test "x$libsout" = "xyes" ; then
-	 shift
-	 continue
-      fi
-      ### Set the flag
-      libsout="yes"
-      ### See if we need the new library
-      if test "x$new_set" = "xyes"; then
-         libs="${newlib} ${rootlibs}"
+      if test $nonew_set = no ; then
+        libs="${newlib} ${rootlibs}"
       else
-         libs=${rootlibs}
+        libs=${rootlibs}
       fi
-      ### If we're on a win32 system, we need to change the -l prefix
-      ### into a .lib suffix, and expend the paths to a backslash
-      ### separated path.
-      if test "$arch" = "win32"; then
-         nlibs=`echo $libs | sed "s@-l\([a-zA-Z0-9]*\)@${libdir}/lib\1.lib@g"`
+      if [ "$arch" = "win32" ]; then
+         nlibs=`echo $libs | sed "s@%prefix%@${exec_prefix}/lib@g"`
          libs=
          for i in $nlibs; do
             libs="$libs '`cygpath -w $i`'"
          done
+         echo $libs ${auxlibs}
       else
-         if test "x$noldflags" = "xno" ; then
-	    out="$out -L${libdir}"
-	 fi
-      fi
-      if test "x$noauxlibs" = "xyes" ; then
-	 out="$out $libs"
-      else
-	 out="$out $libs ${auxlibs}"
+         echo -L${exec_prefix}/lib $libs ${auxlibs}
       fi
       ;;
     --glibs)
-      ### Output graphics an normal libraries
-      ### If the user said --libs --glibs, we don't need to add the
-      ### regular ROOT libraries.
-      if test "x$libsout" = "xno" ; then
-         ### Set the flag
-         libsout="yes"
-         if test "x$new_set" = "xyes" ; then
-         glibs="${newlib} ${rootlibs} ${rootglibs}"
+      if test $nonew_set = no ; then
+        glibs="${newlib} ${rootlibs} ${rootglibs}"
       else
-         glibs="${rootlibs} ${rootglibs}"
+        glibs="${rootlibs} ${rootglibs}"
       fi
-      fi
-      ### If we're on a win32 system, we need to change the -l prefix
-      ### into a .lib suffix, and expend the paths to a backslash
-      ### separated path.
-      if test "$arch" = "win32"; then
-         nlibs=`echo $glibs | sed "s@-l\([a-zA-Z0-9]*\)@${libdir}/lib\1.lib@g"`
+      if [ "$arch" = "win32" ]; then
+         nlibs=`echo $glibs | sed "s@%prefix%@${exec_prefix}/lib@g"`
          glibs=
          for i in $nlibs; do
             glibs="$glibs '`cygpath -w $i`'"
          done
+         echo $glibs ${auxglibs}
       else
-        if test "x$noldflags" = "xno" ; then
-           out="$out -L${libdir}"
-        fi
+         echo -L${exec_prefix}/lib $glibs ${auxglibs}
       fi
-      if test "x$noauxlibs" = "xyes" ; then
-         out="$out $glibs"
-      else
-         out="$out $glibs ${auxlibs}"
-      fi
-      ;;
-    --auxlibs)
-      ### output the auxiliary libraries
-      out="$out $auxlibs"
-      ;;
-    --libdir)
-      ### output the library directory
-      out="$out $libdir"
-      ;;
-    --incdir)
-      ### output the header directory
-      out="$out $incdir"
-      ;;
-    --help)
-      ### Print a help message
-      echo "Usage: `basename $0` [options]"
-      echo ""
-      echo "  --prefix[=dir]        Print or set prefix"
-      echo "  --exec-prefix[=dir]   Print or set execution prefix"
-      echo "  --libs                Print regular ROOT libraries"
-      echo "  --glibs               Print regular + GUI ROOT libraries"
-      echo "  --cflags              Print compiler flags and header path"
-      echo "  --libdir              Print the library directory"
-      echo "  --incdir              Print the header directory"
-      echo "  --auxlibs             Print auxiliary libraries"
-      echo "  --auxcflags           Print auxiliary compiler flags"
-      echo "  --[no]new             Turn on[off] use of libNew.so"
-      echo "  --noauxlibs           Do not print auxiliary/system libraries"
-      echo "  --noauxcflags         Do not print auxiliary compiler flags"
-      echo "  --noldflags           Do not print linker flags"
-      echo "  --version             Print the ROOT version"
-      exit 0
       ;;
     *)
-      ### Give an error
       echo "${usage}" 1>&2
       exit 1
       ;;
   esac
   shift
 done
-
-### Output the stuff
-echo $out
