[config] clean up code; error report on bad --has-
As per Axel's suggestions I made the following changes:

<> fixed macro expansion
<> fixed tabs
<> an error message is formed with each invalid --has- argument.
<> exit code is set to 1 in case of error
<> output is still displayed normally on the first line. Makes it
   backward compatible in case anyone was `head`ing the first line.

Preview:

spectre@localhost ~/sandbox/root/compiled
 (improve-root-config-bash)> ./bin/root-config --python3-version
--has-http --has- --has-pyroot --has-finished ; echo $?
3.8.9 yes yes
--has-: feature name is required!
--has-finished: unknown feature!
1

spectre@localhost ~/sandbox/root/compiled
 (improve-root-config-bash)> ./bin/root-config --libdir --has-asimage
--has-builtin_cling ; echo $?
/.../root/compiled/./lib yes yes
0

diff --git a/config/root-config.in b/config/root-config.in
--- a/config/root-config.in
+++ b/config/root-config.in
@@ -48,7 +48,7 @@ libdir=@libdir@
 incdir=@incdir@
 etcdir=@etcdir@
 tutdir=@tutdir@
-all_features="@all_features"
+all_features="@all_features@"
 features="@features@"
 configargs="@configargs@"
 altcc="@altcc@"
@@ -471,8 +471,13 @@ while test $# -gt 0; do
     --has-*)
       ### Check for feature
       target=`echo $1 | sed 's/--has-//'`
-		found=""
+      found=""
       for feature in $features ; do
+         if test "$target" = "" ; then
+            feature="<invalid>"
+            errors="$errors--has-: feature name is required!\n"
+            break
+         fi
          if test "$feature" = "$target" ; then
             out="$out yes"
             break
@@ -480,16 +485,17 @@ while test $# -gt 0; do
          feature=""
       done
       if test "$feature" = "" ; then
-			for feature in $all_features ; do
-				if test "$feature" = "$target" ; then
-					found="$feature"
-				fi
-			done
-			if test "$found" = "" ; then
-				out="$out --has-$target: unknown feature!"
-			else
-				out="$out no"
-			fi
+         for feature in $all_features ; do
+            if test "$feature" = "$target" ; then
+               found="$feature"
+               break
+            fi
+         done
+         if test "$found" = "" ; then
+            errors="$errors--has-$target: unknown feature!\n"
+         else
+            out="$out no"
+         fi
       fi
       ;;
     --prefix=*)
@@ -862,3 +868,7 @@ done
 
 ### Output the stuff
 echo $out
+if test "$errors" != "" ; then
+   echo -en "$errors"
+   exit 1
+fi
