Better way to get converage info, and a better test ingeneral: use $ROOTSYS/lib/libReflex for running the test suite!
git-svn-id: http://root.cern.ch/svn/roottest/trunk@1851 7c735d0d-823a-0410-acfd-cd159556d4bf

diff --git a/cint/reflex_standalone/Makefile b/cint/reflex_standalone/Makefile
--- a/cint/reflex_standalone/Makefile
+++ b/cint/reflex_standalone/Makefile
@@ -40,27 +40,19 @@ endif
 endif
 ReflexCMakeTest_Run?=no
 
-# for coverage determination
-ifneq ($(CXXFLAGS),)
- DEFCXXFLAGS:=export CXXFLAGS="$(CXXFLAGS)";
-endif
-ifneq ($(subst -ftest-coverage,,$(CXXFLAGS)),$(CXXFLAGS))
- COVLDFLAGS:=-lgcov
-endif
-ifneq ($(LDFLAGS),)
- DEFLDFLAGS:=export LDFLAGS="$(LDFLAGS) $(COVLDFLAGS)";
-endif
-
 ReflexCMakeConfig:
 	$(CMDECHO)echo Configuring Reflex...
 	$(CMDECHO)mkdir -p cmake-build && cd cmake-build && \
-	$(DEFCXXFLAGS) $(DEFLDFLAGS) cmake -DREFLEX_BUILD_TESTS=ON -DREFLEX_ENABLE_TESTS=ON -DCMAKE_COLOR_MAKEFILE=OFF $(ROOTSYS)/cint/reflex > /dev/null || (echo 'Tests skipped.'; touch ../SKIP-CONFIG-ERROR)
+	cmake -DREFLEX_BUILD_TESTS=ON -DREFLEX_ENABLE_TESTS=ON -DCMAKE_COLOR_MAKEFILE=OFF $(ROOTSYS)/cint/reflex > /dev/null || (echo 'Tests skipped.'; touch ../SKIP-CONFIG-ERROR)
 	$(CMDECHO)echo Done.
 
+# We want to test ROOT's libReflex, so remove the one
+# built by CMake. LD_LIBRARY_PATH will then pick up ROOT's.
 ReflexCMakeBuild: ReflexCMakeConfig
 	$(CMDECHO)if ! [ -e SKIP-CONFIG-ERROR ]; then \
 	echo Building Reflex... && \
 	cd cmake-build && $(MAKE) > /dev/null && \
+	rm src/libReflex.${DllSuf} && \
 	echo Done.; \
 	fi
 
