First try with secrets in root repo

diff --git a/.github/workflows/root-docs.yml b/.github/workflows/root-docs.yml
--- a/.github/workflows/root-docs.yml
+++ b/.github/workflows/root-docs.yml
@@ -114,13 +114,7 @@ jobs:
         dnf upgrade -y
         dnf install -y qt5-doctools
         which qhelpgenerator-qt5
-        echo $PATH
 
-    # - name: Verify qhelpgenerator-qt5 installation
-    #   run: |
-    #     which qhelpgenerator-qt5
-    #     qhelpgenerator-qt5 --version
-      
     - name: Apply option overrides
       if: ${{ github.event_name != 'schedule' }}
       env:
@@ -220,7 +214,6 @@ jobs:
         tarnamexz1=${DOC_DIR}.tar
         tar cf $tarnamexz1 ${DOC_DIR}
         xz -T5 -f $tarnamexz1
-        ls -lh ${DOC_LOCATION} # Debug statement to list files and verify tarball creation
 
     #Upload to GitHub as an artifact (optional)
     - name: Upload tar.gz
@@ -236,49 +229,61 @@ jobs:
       with:
         name: rootdoc.tar.xz
         path: ${{env.DOC_LOCATION}}/${{env.DOC_DIR}}.tar.xz
-
-    # - uses: actions/checkout@master
-    # - uses: chrnorm/deployment-action@releases/v1
-    #   name: Create GitHub deployment
-    #   id: test
-    #   with:
-    #     token: ${{ secrets.GITHUB_TOKEN}}
-    #     description: 'Preview my app'
-    #     environment: preview
-
-    # - uses: shallwefootball/s3-upload-action@master
-    #   name: Upload S3
-    #   id: S3
-    #   with:
-    #     aws_key_id: ${{ secrets.OS_APPLICATION_CREDENTIAL_ID }}
-    #     aws_secret_access_key: ${{ secrets.OS_APPLICATION_CREDENTIAL_SECRET}}
-    #     aws_bucket: root
-    #     source_dir: ${{env.DOC_LOCATION}}/${{env.DOC_DIR}}
+        
+    # Install AWS CLI before syncing to S3
+    - name: Install AWS CLI
+      run: |
+        python -m pip install --upgrade pip
+        pip install awscli
     
+    - name: Sync to S3
+      run: |
+        DEST="s3://root/99999_${PR_NUMBER:-}" # if PR, upload in s3://root/99999_<prnumber>
+        aws --endpoint-url https://s3.cern.ch s3 sync --delete build/99999_${PR_NUMBER:-} ${DEST}
+      env:
+        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+        AWS_REGION: "eu-west-1"
+
+    # OpenStack upload works somehow like this
+    # - name: Install OpenStack CLI
+    #   run: |
+    #     dnf install -y python3-openstackclient
+    #     pip install --upgrade openstacksdk
+
+    # - name: Upload Documentation to OpenStack Swift
+    #   run: |
+    #     openstack container create rootdoc
+    #     openstack object create rootdoc ${{env.DOC_LOCATION}}/${{env.DOC_DIR}} --recursive
+
     # - name: Update deployment status (success)
     #   if: success()
     #   uses: chrnorm/deployment-status@releases/v1
     #   with:
     #     token: ${{ secrets.GITHUB_TOKEN }}
-    #     target_url: https://aws-bucket.s3.ap-northeast-2.amazonaws.com/${{steps.S3.outputs.object_key}}/index.html
+    #     target_url: https://adrianduesselberg/rootdoc/index.html  # Replace with the actual URL
     #     state: 'success'
     #     deployment_id: ${{ steps.test.outputs.deployment_id }}
 
-    - name: Install OpenStack CLI
-      run: |
-        dnf install -y python3-openstackclient
-        pip install --upgrade openstacksdk
+    # - name: Sync HTML to the server
+    #   shell: bash
+    #   run: |
+    #     docdir=${{env.DOC_DIR}}
 
-    - name: Upload Documentation to OpenStack Swift
-      run: |
-        openstack container create rootdoc
-        openstack object create rootdoc ${{env.DOC_LOCATION}}/${{env.DOC_DIR}} --recursive
+    #     # Check if the docdir contains 'html'
+    #     if [[ "$docdir" == *html* ]]; then
+    #       rsync --delete -a $docdir/ root.cern.ch:/var/www/root/root/$docdir
+    #       ret=$?
+    #     else
+    #       rsync --delete --exclude release-notes.html -a $docdir/ root.cern.ch:/var/www/root/doc/$docdir
+    #       ret=$?
+    #     fi
 
-    - name: Update deployment status (success)
-      if: success()
-      uses: chrnorm/deployment-status@releases/v1
-      with:
-        token: ${{ secrets.GITHUB_TOKEN }}
-        target_url: https://adrianduesselberg/rootdoc/index.html  # Replace with the actual URL
-        state: 'success'
-        deployment_id: ${{ steps.test.outputs.deployment_id }}
+    #     # upload the archives if necessary
+    #     if [[ "$docdir" != "master" && "$docdir" != "html602" ]]; then
+    #       scp $tarnamegz root.cern.ch:/var/www/root/download/
+    #       scp $tarnamexz2 root.cern.ch:/var/www/root/download/
+    #     fi
+
+    #     # Exit with the return status of the rsync command
+    #     exit $ret
